from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from ..models import Library, User
from ..serializers import LibrarySerializer, SongSerializer, UserSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    CRUD for User.
    list   GET    /api/users/
    create POST   /api/users/
    read   GET    /api/users/{id}/
    update PUT    /api/users/{id}/
    patch  PATCH  /api/users/{id}/
    delete DELETE /api/users/{id}/
    """

    queryset = User.objects.all()
    serializer_class = UserSerializer

    @action(detail=True, methods=["get"], url_path="songs")
    def songs(self, request, pk=None):
        """GET /api/users/{id}/songs/ — all songs generated by this user."""
        user = self.get_object()
        serializer = SongSerializer(user.songs.all(), many=True)
        return Response(serializer.data)

    @action(detail=True, methods=["get"], url_path="library")
    def library(self, request, pk=None):
        """GET /api/users/{id}/library/ — the user's library."""
        user = self.get_object()
        try:
            serializer = LibrarySerializer(user.library)
            return Response(serializer.data)
        except Library.DoesNotExist:
            return Response(
                {"detail": "This user has no library yet."},
                status=status.HTTP_404_NOT_FOUND,
            )
