from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from ..models import Library, User
from ..serializers import LibrarySerializer, SongSerializer, UserSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    CRUD for User.
    list   GET    /api/users/
    create POST   /api/users/
    read   GET    /api/users/{id}/
    update PUT    /api/users/{id}/
    patch  PATCH  /api/users/{id}/
    delete DELETE /api/users/{id}/
    """

    queryset = User.objects.all()
    serializer_class = UserSerializer

    def get_queryset(self):
        """Support ?username=xxx filter."""
        qs = super().get_queryset()
        username = self.request.query_params.get("username")
        if username:
            qs = qs.filter(username=username)
        return qs

    @action(detail=False, methods=["post"], url_path="get-or-create")
    def get_or_create(self, request):
        """
        POST /api/users/get-or-create/
        Body: {"username": "xxx"}          (required)
              {"username": "xxx", "display_name": "My Name"}  (optional)
        Returns existing user or creates a new one. Never errors on duplicate.
        """
        username = (request.data.get("username") or "").strip()
        if not username:
            return Response(
                {"detail": "username is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        user, created = User.objects.get_or_create(
            username=username,
            defaults={
                "display_name": request.data.get("display_name", username),
            },
        )
        serializer = self.get_serializer(user)
        status_code = status.HTTP_201_CREATED if created else status.HTTP_200_OK
        return Response(serializer.data, status=status_code)

    @action(detail=True, methods=["get"], url_path="songs")
    def songs(self, request, pk=None):
        """GET /api/users/{id}/songs/ — all songs generated by this user."""
        user = self.get_object()
        serializer = SongSerializer(user.songs.all(), many=True)
        return Response(serializer.data)

    @action(detail=True, methods=["get"], url_path="library")
    def library(self, request, pk=None):
        """GET /api/users/{id}/library/ — the user's library."""
        user = self.get_object()
        try:
            serializer = LibrarySerializer(user.library)
            return Response(serializer.data)
        except Library.DoesNotExist:
            return Response(
                {"detail": "This user has no library yet."},
                status=status.HTTP_404_NOT_FOUND,
            )
