from django.conf import settings
from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from ..models import Library, User
from ..serializers import LibrarySerializer, SongSerializer, UserSerializer
from ..utils_auth import issue_session_token


class UserViewSet(viewsets.ModelViewSet):
    """
    CRUD for User.
    list   GET    /api/users/
    create POST   /api/users/
    read   GET    /api/users/{id}/
    update PUT    /api/users/{id}/
    patch  PATCH  /api/users/{id}/
    delete DELETE /api/users/{id}/
    """

    queryset = User.objects.all()
    serializer_class = UserSerializer

    def get_queryset(self):
        """Support ?username=xxx filter."""
        qs = super().get_queryset()
        username = self.request.query_params.get("username")
        if username:
            qs = qs.filter(username=username)
        return qs

    @action(detail=False, methods=["post"], url_path="get-or-create")
    def get_or_create(self, request):
        """
        POST /api/users/get-or-create/
        Body: {"username": "xxx"}          (required)
              {"username": "xxx", "display_name": "My Name"}  (optional)
        Returns existing user or creates a new one. Never errors on duplicate.
        Disabled when ALLOW_DISPLAY_NAME_GET_OR_CREATE is not set (Google-only product).
        """
        if not getattr(
            settings, "ALLOW_DISPLAY_NAME_GET_OR_CREATE", False
        ):
            return Response(
                {
                    "detail": "Display-name sign-in is disabled. Sign in via GET /api/auth/google/login/ in the "
                    "browser, POST /api/auth/google/ with an id_token for API clients, or set "
                    "ALLOW_DISPLAY_NAME_GET_OR_CREATE=true for curl/Postman testing only."
                },
                status=status.HTTP_403_FORBIDDEN,
            )
        username = (request.data.get("username") or "").strip()
        if not username:
            return Response(
                {"detail": "username is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        user, created = User.objects.get_or_create(
            username=username,
            defaults={
                "display_name": request.data.get("display_name", username),
            },
        )
        issue_session_token(user)
        data = self.get_serializer(user).data
        data["session_token"] = user.session_token
        status_code = status.HTTP_201_CREATED if created else status.HTTP_200_OK
        return Response(data, status=status_code)

    @action(detail=True, methods=["get"], url_path="songs")
    def songs(self, request, pk=None):
        """GET /api/users/{id}/songs/ — all songs generated by this user."""
        target = self.get_object()
        u = request.user
        if isinstance(u, User) and u.is_authenticated:
            if target.id != u.id:
                return Response(
                    {"detail": "You can only list your own songs."},
                    status=status.HTTP_403_FORBIDDEN,
                )
        serializer = SongSerializer(target.songs.all(), many=True)
        return Response(serializer.data)

    @action(detail=True, methods=["get"], url_path="library")
    def library(self, request, pk=None):
        """GET /api/users/{id}/library/ — the user's library."""
        target = self.get_object()
        u = request.user
        if isinstance(u, User) and u.is_authenticated:
            if target.id != u.id:
                return Response(
                    {"detail": "You can only view your own library."},
                    status=status.HTTP_403_FORBIDDEN,
                )
        try:
            serializer = LibrarySerializer(target.library)
            return Response(serializer.data)
        except Library.DoesNotExist:
            return Response(
                {"detail": "This user has no library yet."},
                status=status.HTTP_404_NOT_FOUND,
            )
