from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from ..models import Library, User
from ..serializers import LibrarySerializer, SongSerializer, UserSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    CRUD for User.
    list   GET    /api/users/
    create POST   /api/users/
    read   GET    /api/users/{id}/
    update PUT    /api/users/{id}/
    patch  PATCH  /api/users/{id}/
    delete DELETE /api/users/{id}/
    """

    queryset = User.objects.all()
    serializer_class = UserSerializer

    def get_queryset(self):
        """Support ?google_id=xxx filter for frontend lookup."""
        qs = super().get_queryset()
        google_id = self.request.query_params.get("google_id")
        if google_id:
            qs = qs.filter(google_id=google_id)
        return qs

    @action(detail=False, methods=["post"], url_path="get-or-create")
    def get_or_create(self, request):
        """
        POST /api/users/get-or-create/
        Body: {google_id, email, display_name, session_token}
        Returns the existing user or creates a new one. Never errors on duplicate.
        """
        google_id = request.data.get("google_id", "").strip()
        if not google_id:
            return Response({"detail": "google_id is required."}, status=status.HTTP_400_BAD_REQUEST)

        user, created = User.objects.get_or_create(
            google_id=google_id,
            defaults={
                "email": request.data.get("email", f"{google_id}@local.dev"),
                "display_name": request.data.get("display_name", google_id),
                "session_token": request.data.get("session_token", ""),
            },
        )
        serializer = self.get_serializer(user)
        status_code = status.HTTP_201_CREATED if created else status.HTTP_200_OK
        return Response(serializer.data, status=status_code)

    @action(detail=True, methods=["get"], url_path="songs")
    def songs(self, request, pk=None):
        """GET /api/users/{id}/songs/ — all songs generated by this user."""
        user = self.get_object()
        serializer = SongSerializer(user.songs.all(), many=True)
        return Response(serializer.data)

    @action(detail=True, methods=["get"], url_path="library")
    def library(self, request, pk=None):
        """GET /api/users/{id}/library/ — the user's library."""
        user = self.get_object()
        try:
            serializer = LibrarySerializer(user.library)
            return Response(serializer.data)
        except Library.DoesNotExist:
            return Response(
                {"detail": "This user has no library yet."},
                status=status.HTTP_404_NOT_FOUND,
            )
