# Generated by Django 5.1.7 on 2026-04-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_ai_generation_request_external_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='google_id',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
