"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Load .env from the backend directory (safe if file doesn't exist)
load_dotenv(Path(__file__).resolve().parent.parent / ".env")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-m^nw1!&$u9_ng2q=d6nf-&hq*#ad@aw__q_^vqxc#sd=&ii!k("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "songs",
    "rest_framework",
]

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "songs.authentication.BearerSessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- CORS (allow React dev server) ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# --- Song generation (Strategy pattern) ---
# GENERATOR_STRATEGY: "mock" (offline) | "suno" (api.sunoapi.org)
GENERATOR_STRATEGY = os.environ.get("GENERATOR_STRATEGY", "mock").strip().lower()
SUNO_API_KEY = os.environ.get("SUNO_API_KEY", "").strip()
SUNO_API_BASE_URL = os.environ.get(
    "SUNO_API_BASE_URL", "https://api.sunoapi.org"
).strip()
SUNO_MODEL = os.environ.get("SUNO_MODEL", "V4_5ALL").strip()
# Required by Suno "Generate Music" API; polling is used instead of handling callbacks.
SUNO_CALLBACK_URL = os.environ.get(
    "SUNO_CALLBACK_URL", "https://example.com/suno-callback-placeholder"
).strip()

# Google Sign-In: Web client ID (used to verify id_token and in OAuth authorization URL).
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "").strip()
# Required for browser OAuth (authorization code) flow: GET /api/auth/google/login/ → callback.
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", "").strip()
# Must match an "Authorized redirect URI" in Google Cloud (Web client). Default matches runserver.
GOOGLE_OAUTH_REDIRECT_URI = os.environ.get(
    "GOOGLE_OAUTH_REDIRECT_URI",
    "http://127.0.0.1:8000/api/auth/google/callback/",
).strip()
# Where the API sends the user after Google login (SPA receives session in query string).
GOOGLE_OAUTH_FRONTEND_BASE = os.environ.get(
    "GOOGLE_OAUTH_FRONTEND_BASE",
    "http://localhost:5173",
).strip().rstrip("/")
# When False (default), POST /api/users/get-or-create/ is disabled; sign-in is Google only.
# Set to true only for local curl/Postman testing without a browser.
_ALLOW_RAW = os.environ.get("ALLOW_DISPLAY_NAME_GET_OR_CREATE", "").strip().lower()
ALLOW_DISPLAY_NAME_GET_OR_CREATE = _ALLOW_RAW in ("1", "true", "yes")
