import uuid
from django.db import models

from .enums import GenerationStatus
from .user import User
from .playback_session import PlaybackSession


class Song(models.Model):
    """
    Core domain entity. A song is generated by a User and carries its
    AI generation status throughout its lifecycle.
    shareLink is optional ([0..1] in the domain model).
    A Song is played via 0..1 PlaybackSession.
    """

    song_id           = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    user              = models.ForeignKey(User, on_delete=models.CASCADE, related_name="songs")
    # Song (0..*) played via PlaybackSession (0..1)
    playback_session  = models.ForeignKey(
        PlaybackSession,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="songs",
    )
    title             = models.CharField(max_length=255)
    audio_file_url    = models.URLField(blank=True)
    generation_status = models.CharField(
        max_length=20,
        choices=GenerationStatus.choices,
        default=GenerationStatus.DRAFT,
    )
    created_at        = models.DateTimeField(auto_now_add=True)
    is_favorite       = models.BooleanField(default=False)
    is_draft          = models.BooleanField(default=True)
    share_link        = models.URLField(blank=True)  # optional [0..1]

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.title} ({self.get_generation_status_display()})"
