import uuid
from django.db import models


class GenerationStatus(models.TextChoices):
    IN_PROGRESS = "IN_PROGRESS", "In Progress"
    COMPLETED = "COMPLETED", "Completed"
    FAILED = "FAILED", "Failed"
    DRAFT = "DRAFT", "Draft"


class Occasion(models.TextChoices):
    BIRTHDAY = "BIRTHDAY", "Birthday"
    WEDDING = "WEDDING", "Wedding"
    ANNIVERSARY = "ANNIVERSARY", "Anniversary"
    GRADUATION = "GRADUATION", "Graduation"
    GENERAL = "GENERAL", "General"


class MoodTone(models.TextChoices):
    HAPPY = "HAPPY", "Happy"
    SAD = "SAD", "Sad"
    ROMANTIC = "ROMANTIC", "Romantic"
    ENERGETIC = "ENERGETIC", "Energetic"
    CALM = "CALM", "Calm"


class SingerTone(models.TextChoices):
    MALE_DEEP = "MALE_DEEP", "Male Deep"
    MALE_LIGHT = "MALE_LIGHT", "Male Light"
    FEMALE_DEEP = "FEMALE_DEEP", "Female Deep"
    FEMALE_LIGHT = "FEMALE_LIGHT", "Female Light"
    NEUTRAL = "NEUTRAL", "Neutral"


class User(models.Model):
    """
    A registered user of the platform.
    Authentication (Google OAuth) is outside scope for this exercise;
    the fields below reflect the domain model attributes exactly.
    """

    user_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    google_id = models.CharField(max_length=255, unique=True)
    email = models.EmailField(unique=True)
    display_name = models.CharField(max_length=255)
    session_token = models.CharField(max_length=500, blank=True)

    class Meta:
        ordering = ["display_name"]

    def __str__(self):
        return self.display_name


class PlaybackSession(models.Model):
    """
    Represents an active or paused playback state for a song.
    loopStart and loopEnd are optional ([0..1] in the domain model).
    """

    session_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    current_position = models.FloatField(
        default=0.0, help_text="Playback position in seconds"
    )
    loop_start = models.FloatField(
        null=True, blank=True, help_text="Loop start in seconds"
    )
    loop_end = models.FloatField(null=True, blank=True, help_text="Loop end in seconds")
    equalizer_settings = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return f"Session {self.session_id}"


class Song(models.Model):
    """
    Core domain entity. A song is generated by a User and carries its
    AI generation status throughout its lifecycle.
    shareLink is optional ([0..1] in the domain model).
    A Song is played via 0..1 PlaybackSession.
    """

    song_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="songs")
    # Song (0..*) played via PlaybackSession (0..1)
    playback_session = models.ForeignKey(
        PlaybackSession,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="songs",
    )
    title = models.CharField(max_length=255)
    audio_file_url = models.URLField(blank=True)
    generation_status = models.CharField(
        max_length=20, choices=GenerationStatus.choices, default=GenerationStatus.DRAFT
    )
    created_at = models.DateTimeField(auto_now_add=True)
    is_favorite = models.BooleanField(default=False)
    is_draft = models.BooleanField(default=True)
    share_link = models.URLField(blank=True)  # optional [0..1]

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.title} ({self.get_generation_status_display()})"


class Library(models.Model):
    """
    A User owns exactly one Library (1..1).
    A Library contains zero or more Songs (0..*).
    filterCriteria is optional ([0..1] in the domain model).
    totalCount reflects the number of songs currently in the library.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="library")
    songs = models.ManyToManyField(Song, blank=True, related_name="libraries")
    filter_criteria = models.CharField(max_length=500, blank=True)  # optional [0..1]
    total_count = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name_plural = "libraries"

    def __str__(self):
        return f"{self.user.display_name}'s Library"

    def sync_total_count(self):
        self.total_count = self.songs.count()
        self.save(update_fields=["total_count"])


class SongPrompt(models.Model):
    """
    Captures the creative input that defines a Song.
    Exactly one SongPrompt maps to exactly one Song (1..1 both ways).
    """

    prompt_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    song = models.OneToOneField(Song, on_delete=models.CASCADE, related_name="prompt")
    title = models.CharField(max_length=255)
    occasion = models.CharField(max_length=20, choices=Occasion.choices)
    mood_and_tone = models.CharField(max_length=20, choices=MoodTone.choices)
    singer_tone = models.CharField(max_length=20, choices=SingerTone.choices)
    description = models.TextField(blank=True)

    def __str__(self):
        return f"Prompt: {self.title} ({self.get_occasion_display()})"


class AIGenerationRequest(models.Model):
    """
    Created when a SongPrompt triggers the AI generation pipeline.
    Exactly one request per prompt (1..1).
    errorMessage is optional ([0..1] in the domain model).
    """

    request_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    prompt = models.OneToOneField(
        SongPrompt, on_delete=models.CASCADE, related_name="generation_request"
    )
    submitted_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=20,
        choices=GenerationStatus.choices,
        default=GenerationStatus.IN_PROGRESS,
    )
    error_message = models.TextField(blank=True)  # optional [0..1]

    def __str__(self):
        return f"Request {self.request_id} – {self.get_status_display()}"


class SharedSong(models.Model):
    """
    Produced when a Song is shared (Song produces 0..1 SharedSong).
    accessibleByGuest controls whether non-registered users can access the link.
    """

    share_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    song = models.OneToOneField(
        Song, on_delete=models.CASCADE, related_name="shared_song"
    )
    share_link = models.URLField(unique=True)
    shared_at = models.DateTimeField(auto_now_add=True)
    accessible_by_guest = models.BooleanField(default=False)

    def __str__(self):
        return f"Shared: {self.song.title}"


class Draft(models.Model):
    """
    A Song can be saved as one or more Drafts (0..* in the domain model).
    retentionPolicy determines how long a draft is kept before auto-deletion.
    """

    draft_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    song = models.ForeignKey(Song, on_delete=models.CASCADE, related_name="drafts")
    saved_at = models.DateTimeField(auto_now_add=True)
    is_submitted = models.BooleanField(default=False)
    retention_policy = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ["-saved_at"]

    def __str__(self):
        return f"Draft of '{self.song.title}' at {self.saved_at:%Y-%m-%d %H:%M}"
